version: '3.2'
services:
    jupyter:
        working_dir: /notebooks
        build: .
        volumes:
            - .:/notebooks
        ports:
            - "8888:8888"
        expose:
            - "8888"
        command: jupyter notebook --allow-root --no-browser --NotebookApp.token='' --ip=0.0.0.0 --port=8888 
